base_global_planner: "navfn/NavfnROS"
# base_local_planner: "dwa_local_planner/DWAPlannerROS"

max_planning_retries: 3
recovery_behavior_enabled: true
clearing_rotation_allowed: false

#recovery_behaviors:
#- name: 'forward_recovery'
#- name: 'backward_recovery'

planner_frequency: 2.5
controller_frequency: 10.0

oscillation_timeout: 15.0
oscillation_distance: 0.20

controller_patience: 4.0
planner_patience: 2.0

