global_frame: map
robot_base_frame: pelvis

obstacle_range: 2.5 #Map updated with obstacles in 2.5 meters
raytrace_range: 3.0 #Range where we raytrace the free space

max_obstacle_height: 5.0
min_obstacle_height: 0.2

footprint: [[0.50, 0.40], [0.50, -0.40], [-0.50, -0.40], [-0.50 ,0.40]]
#robot_radius: 0.4

transform_tolerance: 1.0
#map_type: costmap


# observation_sources: velodyne d435i
# velodyne: {sensor_frame: pelvis, data_type: PointCloud2, topic: /velodyne_points, marking: true, clearing: true}
#d435i: {sensor_frame: pelvis, data_type: PointCloud2, topic: /D435i_camera/depth/color/points, marking: true, clearing: true}
