DWAPlannerROS:

  max_vel_trans: 0.20
  min_vel_trans: 0.05

  max_vel_x: 0.175
  min_vel_x: -0.175

  max_vel_y: 0.175
  min_vel_y: -0.175

  max_vel_theta: 0.18
  min_vel_theta: 0.05 #DWA consider absolute value

  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_th: 3.2

  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.30
  latch_xy_goal_tolerance: false

  trans_stopped_vel: 0.04
  theta_stopped_vel: 0.05

  sim_time: 1.7
  sim_granularity: 0.025

  path_distance_bias: 32 #Weight to follow global path, default: 32
  goal_distance_bias: 24.0 #Weight to reach global target, default: 24
  occdist_scale: 0.01 #The weighting for how much the controller should attempt to avoid obstacles default 0.01

  oscillation_reset_dist: 0.20
  oscillation_reset_angle: 0.40

  scaling_speed: 0.25 #The absolute value of the velocity at which to start scaling the robot's footprint, in m/s
  max_scaling_factor: 0.2 #The maximum factor to scale the robot's footprint by

  vx_samples: 3
  vy_samples: 10
  vth_samples: 20
